### ISSUE TITLE
bug: adding recommended: true can break ruleset loading?

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#119]
A quirk with working on custom rulesets is that it seems to try to load periodically, not on save. If I try adding `recommended: true` but type it slowly, I get errors about failure to load because it's not a boolean...

**To Reproduce**

Given .spectral.yml with a content of:

```
extends: spectral:oas2
rules:
  paths-camelCase:
    description: All YAML and JSON paths MUST follow fields-camelCase
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^([a-z]+([A-Z][a-z0-9]*)*[\/]{1})+([a-z]+([A-Z][a-z0-9]*))"
```

I type `recommended: ` but do not save, then I see an error. 

> Spectral ruleset could not be loaded. /rules/schema-names-pascal-case/recommended should be boolean /rules/schema-names-pascal-case should be string /rules/schema-names-pascal-case should be equal to one of the allowed values /rules/schema-names-pascal-case should be boolean /rules/schema-names-pascal-case should be array /rules/schema-names-pascal-case should match exactly one schema in oneOf

**Expected behavior**

I do not expect reloads of the ruleset preview on change, or if it does work then it should be putting these sorts of concerns into the diagnostics panel so I can fix them easily and not have big red boxes thrown up.

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/67381/65068793-513f5d00-d957-11e9-93a5-23a89c1dd98d.gif)

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.2
 - OS: macOS

**Additional context**
