### ISSUE TITLE
bug: custom rules wont load operation

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#120]
I made a custom rule which is complaining about paths, but when I click on them I get a blank view panel, even though the cursor is jumping to the right place in text view. 

**To Reproduce**

Write a custom rule against paths. 

```
extends: spectral:oas2
rules:
  paths-camelCase:
    description: All YAML and JSON paths MUST follow fields-camelCase
    severity: error
    recommended: true
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^([a-z]+([A-Z][a-z0-9]*)*[\/]{1})+([a-z]+([A-Z][a-z0-9]*))"
```

**Expected behavior**

When I enter this in .spectral.yml and reload, I see custom errors showing up in diagnostic panel correctly, but when I click on them the form panel is empty. I expect to see the path or operation or something. 

**Screenshots**

![custom rules wont load operation](https://user-images.githubusercontent.com/67381/65070055-ed6a6380-d959-11e9-814f-e8449b171cce.gif)
