### ISSUE TITLE
Add support for setting "nullable" keyword on schema objects 

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#132]
Add support for the OpenAPIv3 "nullable" keyword through the form-based editor.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-20

## Nullable

Neither OAS2 or OAS3.0 allow `"type: 'null'"` or  `"type: ['null']"`, so if the null type is selected in JSE then we should output the following:

```yaml
# oas2
type: string
x-nullable: true  # the x- means this is an extension

# oas3.0
type: string
nullable: true

# what we do now (JSON Schema) 
type:
  - string
  - 'null'

# oas3.1 deprecated
type: string
nullable: true    # this is deprecated but valid 

# oas3.1 better (same as what we do now)
type:
  - string
  - 'null'
```

😅🤪🤔🤯🤨😞 right? Nobody is excited but the point is the divergence has been solved in 3.1, yay, but until then we have to handle these variations. 

Studio needs to be aware of if its editing an OAS2 or OAS3.0 file, then use the appropriate keywords. We did this for OAS3 `deprecated` vs OAS2 `x-deprecated` recently #223, so it seems like we can add a hack to do something similar. 

It will almost certainly be a hack, and this hack will have limitations. The way studio detects OAS2/OAS3/"JSON Schema" is currently somewhat flawed. If there is `swagger: 2.0` then its OAS2, if `openapi: 3.0.x` then its OAS3, otherwise if it looks like it might be a JSON Schema (type: foo was found) then we'll go with that. This is a bit of a simplification, but its roughly the case. This means, even after this change, JSE will not be able to help anyone who is using $ref to external files for their models, because we have no way of knowing if the $reffed model is "JSON Schema Proper" or "OpenAPI Schema Object".

This is being attacked systematically across all of our tooling post-v2, with "multiple dialect support". This issue is about giving us a quick win on this nullable situation ASAP.
