### ISSUE TITLE
Form for standalone model's adds an extra "value" property to examples

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#176]
**Reproduce**

1. Create a standalone model
2. Add an example
3. Notice the result has an extra "value" property nested in each example:

```yaml
x-examples:
  example:
    value:
      latitude: 123
      longitude: 456
```

This is valid for embedded openapi 3 definitions, but not for standalone json schema models.
