### ISSUE TITLE
JSON Schema Viewer duplicate $refs causes overlapping text

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#186]
**Describe the bug**
When there are multiple $refs pointing to the same location, the JSON Schema Viewer treats them as the same expand/collapse which results in the text overlapping.

**To Reproduce**

1. Add the following model:

```yaml json_schema
type: object
properties:
  low_resolution:
    $ref: >-
      https://stoplight.io/api/nodes.raw?srn=gh/stoplightio/sample-specs/reference/instagram/instagram.yaml/definitions/ImageInfo
  standard_resolution:
    $ref: >-
      https://stoplight.io/api/nodes.raw?srn=gh/stoplightio/sample-specs/reference/instagram/instagram.yaml/definitions/ImageInfo
```

2. Collapse one of the rows and notice the text is scrunched.

**Expected behavior**

**Screenshots**
![2019-10-10 23 34 35](https://user-images.githubusercontent.com/7423098/66624626-8fc2e300-ebb6-11e9-81ff-35ed8b4df8fc.gif)

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.5
 - OS: MacOS
