### ISSUE TITLE
Path parameters are created in inconsistent way

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#188]
When creating path parameters from right-clicking in the API sidebar menu, I get:

```yaml
      - type: string
        name: entityID
        in: path
        required: true
```

When creating a path parameter from the Forms view, I get:

```yaml
      - schema:
          type: string
        name: entityID
        in: path
        required: true
```

This was an OpenAPIv3 document.

**Comment by dgrstl** [comment]
Additionally, when doing this in forms view it does not default to string, it defaults to no type.

**Comment by rossmcdonald** [comment]
@dgrstl I'm not able to reproduce that. Can you provide an example?

**Comment by StoplightDeb** [comment]
@mallachari - what release is this?

**Comment by mallachari** [comment]
@StoplightDeb I don't see this commit in 1.7 branch so it should go to 1.8 then

**Comment by chris-miaskowski** [comment]
Looks good, will create
```
- schema:
          type: string
        name: entityID
        in: path
        required: true
```
in both cases
