### ISSUE TITLE
"Property Examples" are not displayed in Read View or Docs

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#194]
**User story.**
As a user who has defined an `example` for any sort of property in a schema, or a parameter, I would expect to see the example show up in the docs view. 

**Is your feature request related to a problem?**

When I add an `example` to any parameter, or inside the schema object, I would expect to see it showing up in the docs and read view. 

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/67381/66872848-35a39280-efa7-11e9-8494-8e6bd51bfde9.png">

This is different to request or response examples, the `example` keyword is for examples for a specific thing. 

**Describe the solution you'd like**

Show `example`, `default` and `deprecated` keywords, like our friends over at ReDoc. 

<img width="318" alt="image" src="https://user-images.githubusercontent.com/67381/66872984-3531da00-ef5c-11e9-91b1-c9aabbb5fcec.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/67381/66872936-07e52c00-ef5c-11e9-90cc-a4ddf6bed370.png">

Similar but different to https://github.com/stoplightio/studio/issues/134, which is about adding support for the `example` keyword to Form View. 

**Additional context**

Examples in OpenAPI / JSON Schema are weird. These slides should help illustrate example types if you skip through a bit. https://docs.google.com/presentation/d/15CgYrnXlatmMdjaQfBznmCi3fiHuckahpEbCJ2kirxY/edit#slide=id.g52221cb4b0_0_126

**Comment by philsturgeon** [comment]
Should work with allOf'ed examples:

```json
      "put": {
        "operationId": "PUT_todos",
        "summary": "Update Todo",
        "tags": [
          "Todos"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "./models/todo-partial.v1.json",
              "example": {
                "name": "my todo's new name",
                "completed": false
              }
              "allOf": [
                {
                  "$ref": "./models/todo-partial.v1.json"
                },
                {
                  "example": {
                    "name": "my todo's new name",
                    "completed": false
                  }
                }
              ]
            }
          }
        ],
```

**Comment by chris-miaskowski** [comment]
Almost there, it looks good with the query param but not with the body nor path param.

Try with the following API:

```yaml
openapi: 3.0.0
info:
  title: Cars API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/cars/{path-with-example}':
    get:
      summary: Get all cars
      tags: []
      responses: {}
      operationId: get-cars
      parameters:
        - schema:
            type: string
            example: c
            enum:
              - a
              - b
              - c
            default: a
          in: query
          name: param-with-example
          example: b
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/model-with-examples.v1.yaml
    parameters:
      - schema:
          type: string
          enum:
            - x
            - y
            - z
          default: x
          example: y
          maxLength: 0
        name: path-with-example
        in: path
        required: true
components:
  schemas: {}
```

and model

```yaml
title: model-with-examples
type: object
properties:
  animal:
    type: string
    example: bunny
  allOf:
    allOf:
      - properties:
          name:
            type: number
            default: 1234
            example: '123'
      - properties:
          type:
            type: string
            default: a
            deprecated: true
            enum:
              - a
              - b
              - c
              - d
            example: b
    type: object
```

![examples-not-present](https://user-images.githubusercontent.com/29548931/69241881-fbc63d00-0b9f-11ea-9786-401e1155e05d.gif)
