### ISSUE TITLE
Creating model property with allOf and $ref confuses forms view

### ISSUE THREAD

**Issue by sensibleish** [stoplightio/studio#203]
**Describe the bug**

When creating a model using Forms view, adding a property of type `allOf` with a `$ref` item generates errors and does not update the Write view or persist the changes, even though Read view shows the correct result.

**To Reproduce**

1. Create a new model
2. Change the default `id` property to type `allOf`
3. Create a child property
4. Change the child property type from `object` to `$ref` (and observe that there are already errors appearing in the lower-right corner of the window)
5. Enter a valid reference URI
6. Observe that the Read view correctly reflects the schema as entered in the Forms view.
7. Change to the Write view.

**Expected behavior**

The Write view should correctly reflect the schema, for example:

```yaml
title: Restaurant
type: object
properties:
  id:
    allOf:
      - $ref: ./image-asset.v1.yaml
```

Instead, it shows:

```yaml
title: Restaurant
type: object
properties:
  id:
    allOf:
      - {}
    type: object
```

That's what is persisted into the underlying file.

**Screenshots**
<img width="624" alt="Forms view" src="https://user-images.githubusercontent.com/1753270/67148661-c94eba80-f256-11e9-884e-6f354a2b1444.png">

<img width="631" alt="Read view" src="https://user-images.githubusercontent.com/1753270/67148663-d075c880-f256-11e9-977a-619d350dd06a.png">

<img width="640" alt="Write view" src="https://user-images.githubusercontent.com/1753270/67148664-d4094f80-f256-11e9-9b22-684326cd00a4.png">

**Environment**
 - Studio version: 1.2.0 (1.2.0.7335)
 - OS: Mac OS 10.15
