### ISSUE TITLE
Studio should re-format imported files

### ISSUE THREAD

**Issue by P0lip** [stoplightio/studio#232]
**User story.**
As a Studio user, spec (oas2, oas3, json schema) file with no syntax errors I import to Studio is formatted according to the defaults used in Studio.

**Comment by StoplightDeb** [comment]
@P0lip can you please clarify what "text files" are?  Literally just any non-image file that one could possibly import into Studio?

**Comment by chris-miaskowski** [comment]
Hey @P0lip and @StoplightDeb I will test:
- html
- json
- yaml
- markdown

**Comment by chris-miaskowski** [comment]
Given

```yaml
  title: model-with-examples
  type: object
properties:
    animal:
      type: string
      example: bunny
  allOf:
    allOf:
      - properties:
          name:
            type: number
            default: 1234
            example: '123'
      - properties:
          type:
                        type: string
            default: a
            deprecated: true
            enum:
              - a
              - b
              - c
              - d
            example: b
    type: object
```

I get 

![image.png](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/5aa36063-e0b1-4ed9-8798-9e7554debc80)

Do we support yaml files?


Given:

```json
{
      "title": "xxxx",
"type": "array",
	  "items": {
			    "type": "object",
    "properties": {
      "a": {
        "type": 
	
	[

          "string",
          "object"
        ],
	        "properties"	: 
		{
          "all": {
            "anyOf": [
              {
                "properties": {
                  "x": {
                    "type": "string"
                  }
                }
                  }          ,



              {
                "properties": {
                  "y":                       {
                    "type":         "string"
                  }
                }
              }
            ],
            "type": "object"
          }
        }
      }
    }
  }
}
```

I get

![image.png](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/0dc92445-aba7-4ff8-abf5-de957606c559)

**Stopping here**, looks broken.

Also, should I expect re-formatting when I paste a text to the editor or any when I open a file?
