### ISSUE TITLE
parameter type error

### ISSUE THREAD

**Issue by MonsterRob** [stoplightio/studio#287]
```
parameters:
      - type: string
        name: space_id
        in: path
        required: true
      - type: string
        name: app_id
        in: path
        required: true
```
This can be rended by swagger editor
