### ISSUE TITLE
Default value not correct type

### ISSUE THREAD

**Issue by johandalabacka** [stoplightio/studio#292]
Then setting a default value for Query parameter of type number/integer/boolean is the default value created as a string in the yaml-file

```yaml
- schema:
            type: number
            default: '4'
          in: query
          name: a
          required: true
```

The same error shows for Path params also. However for default in Models is it the correct type but then is the example field of wrong type

```yaml
properties:
        a:
          type: number
          default: 45
          example: '45'
```

The program itself detects this and shows it as issues

| Type | Line | Message|
|------|-----|----------|
|!|115 |`example` property type should be number|
|!|119 |`example` property type should be number|

and so on

Using latest Stoplight Studio - Version 1.8.0 (1.8.0.10358)
