### ISSUE TITLE
"Components" should support Reference Objects

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#297]
All components are allowed to contain a reference object for a collection of components, for example:

```
components:
  securitySchemes:
    $ref: ../common/security.v1.yaml#/securitySchemes
```

Forms gets a bit confused in this case:

![image](https://user-images.githubusercontent.com/1297859/72372983-6cd42d80-36d5-11ea-8a21-9aeb7da2c2b0.png)

_Originally posted by @josephgardner in https://github.com/stoplightio/studio/issues/202#issuecomment-574320367_

See the OAS 3.0 specification for more details: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#components-object

**Comment by svassaux** [comment]
what's the status on this one? is it updated in v2?

**Comment by lottamus** [comment]
@svassaux we still do not support referencing the entire security schemes object, however we do support referencing individual security schemes:

```yaml
components:
  securitySchemes:
    apiKey:
      $ref: ../common/security.v1.yaml#/securitySchemes/apiKey
security:
  - apiKey: []
```
