### ISSUE TITLE
Stoplight unnecessarily rewrites response codes from numbers to strings

### ISSUE THREAD

**Issue by BigBlueHat** [stoplightio/studio#298]
**Describe the bug**
Currently, Stoplight will quote all HTTP status codes if they've previously been written as numbers. This seems due to this bug: https://github.com/stoplightio/yaml/issues/34

It'd be great to be able to use numbers for status codes--or at least not to have them rewritten.

**To Reproduce**

Given this OpenAPI document:
```yaml
paths:
  /thing
    get:
      response:
        200:
          content: {}
```
Stoplight rewrites it to:
```yaml
paths:
  /thing
    get:
      response:
        '200':
          content: {}
```

**Expected behavior**
I'd love to use numbers for status codes as there's no YAML nor OpenAPI restriction.
