### ISSUE TITLE
Path Parameters on Operation Objects are not manageable via the Form editor

### ISSUE THREAD

**Issue by BigBlueHat** [stoplightio/studio#329]
**Describe the bug**
Somewhat related to https://github.com/stoplightio/spectral/issues/954

Stoplight doesn't display Path Parameters expressed on the Operation Object. Sometimes those are simply "misplaced" Path Parameters--which would be better put directly on the Path Object--but sometimes they are valid overrides or additions. Currently Stoplight doesn't display them nor allow the user to edit them. Would be great if it could, though. 😃 

**To Reproduce**

```yaml
  /pet/{petId}:
    get:
      tags:
      - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      parameters: # these don't show in Studio...
      - name: petId
        in: path
        description: ID of pet to return
        required: true
        schema:
          type: integer
          format: int64
```

**Expected behavior**
Would love to be able to edit Path Parameters on Operation Objects from the Form editor.
