### ISSUE TITLE
Desktop Studio does not recognize global tags

### ISSUE THREAD

**Issue by jmhansen** [stoplightio/studio#347]
**Describe the bug**
The linter gives a warning that 'Operation tags should be defined in global tags.'  But if I manually add global tags to the spec, the application does not recognize them or add them to the tags UI.  

**To Reproduce**

1. Given an OpenAPI document with a global tags section:
```
tags:
  - name: todo
    description: An empty path that needs to be filled out or removed.
  - name: draft
    description: Documentation in progress but incomplete.
  - name: complete
    description: Documentation is complete
```
2. Click this button to add tags.
3. There are no tags listed (unless they have been added as local tags elsewhere)

**Expected behavior**
Any global tags should be selectable in the tags dropdown.

**Screenshots**
![Screen Shot 2020-03-04 at 10 33 21 AM](https://user-images.githubusercontent.com/10427685/75901177-c1597680-5e03-11ea-9c7e-6b1b23bcf224.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.10.0 (1.10.0.16134)
 - OS: macOS 10.15.3 (Catalina)
