### ISSUE TITLE
Example of number and boolean are stored as strings

### ISSUE THREAD

**Issue by checkin247** [stoplightio/studio#349]
**Describe the bug**
Example for model (schema) properties of either 'number' or 'boolean' are in quotes.
![image](https://user-images.githubusercontent.com/12472764/76100490-0381e400-5fcd-11ea-817e-a042d4578e3b.png)
![image](https://user-images.githubusercontent.com/12472764/76100550-1b596800-5fcd-11ea-90ba-0900d3ab86ef.png)
Starting prism shows violation of data type: `Violation: response.body.data.services[0].inclusive should be boolean`.
There is no linting issue.
Editing the model in a text editor to remove the quotes, fix the problem only temporary. Next time you change some property in the model, the quotes are automatically added again.

```
title: Service
type: object
description: A service or product
properties:
  quantity:
    type: number
    description: Quantity combined with the pricing type.
    example: '1'
    minimum: 1
    maximum: 10000
    multipleOf: 1
  inclusive:
    type: boolean
    default: false
    description: Inclusive (as free) or billed separately
    example: 'false'
```

**To Reproduce**

1. Create a model
2. Create a number property with an example
3. Create a boolean property with an example
4. Open the example in a text editor and check the value of the example property of type number and boolean you created. The example values will be in quotes!

**Expected behavior**
Example values of propterty types 'boolean' and 'number' should _not_ be in quotes.

```
title: Service
type: object
description: A service or product
properties:
  quantity:
    type: number
    description: Quantity combined with the pricing type.
    example: 1
    minimum: 1
    maximum: 10000
    multipleOf: 1
  inclusive:
    type: boolean
    default: false
    description: Inclusive (as free) or billed separately
    example: false
```

**Environment (remove any that are not applicable):**
 - Studio version: [1.10.0]
 - OS: [Windows 10]
 - Browser: [Electron 8.0.0 / chrome 80.0.3987.86]
 - node: 12.13.0
![image](https://user-images.githubusercontent.com/12472764/76099726-d1bc4d80-5fcb-11ea-8d17-c599a08a4ac3.png)

**Additional context**
Prism reports violation when responding with the model or using in payload.
Manually removing the quotes makes prism work, but once modified with Stoplight Studio it reocures.

> The bug reports #292 and #319  report similar problems.
https://github.com/stoplightio/studio/issues/292
reports the same issue in query parameters.
The issue was closed as fixed in version 1.10.0
I have the same issue in version 1.10.0 in the model (not seen any issues in query parameters).
