### ISSUE TITLE
Integer hexadecimal values are converted to decimal when switching between views

### ISSUE THREAD

**Issue by maennel** [stoplightio/studio#356]
**Describe the bug**
Integer maximum, minimum and default values are converted to decimal format when being edited in the form view, despite originally being in hexadecimal.

**To Reproduce**

1. Given this OpenAPI document:
```
openapi: 3.0.0
info:
  title: test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    testSchema:
      title: testSchema
      type: object
      properties:
        value:
          type: integer
          default: 0x0c
          minimum: 0x00
          maximum: 0x10
```
2. Switch from the code view to the form view and open the "Additional properties" view.
3. See that all values are displayed in decimal format.
4. Change the default value to 13 (decimal), go back to code view and see that all values were converted to decimal: 
```
      ...
      properties:
        value:
          type: integer
          default: 13
          minimum: 0
          maximum: 16
```
5. Reset values to their hex value and go back to the "Additional properties" view. I.e. reset to:
```
      ...
      properties:
        value:
          type: integer
          default: 0x0d
          minimum: 0x00
          maximum: 0x10
```
6. Set default value to 0x0e (hex), switch to the code view again and see that the default value now holds a string (which will be complained about by the linter).

```
      ...
      properties:
        value:
          type: integer
          default: '0x0e'
          minimum: 0
          maximum: 16
```

**Expected behavior**
The original representation of values should be preserved to minimize version control changes. The Form view should support hexadecimal values.

**Environment (remove any that are not applicable):**
 - Studio version: 1.10.2
 - OS: Ubuntu 18.04
 - Browser: Chrome 80
