### ISSUE TITLE
Could not dereference ...

### ISSUE THREAD

**Issue by SiBell** [stoplightio/studio#373]
**Describe the bug**
The published documentation fails to render a JSON Schema from an External URL. Displaying a "Could not dereference" error. 

**To Reproduce**

1. Here is external url I enter into studio: https://api.birminghamurbanobservatory.com/schemas/platform-get-response-body.json . I'm setting this as the body of a 200 response from a POST request.
2. I then commit the changes, click publish, and follow the link to view the live docs in my browser.
3. When I go to view the response body in the rendered docs I see the "Could not dereference" error. See screenshot below.

**Expected behavior**
The schema would be rendered correctly. There's a screenshot below showing what I'd expect.

**Screenshots**

Here's the error I see:

<img width="930" alt="Screenshot 2020-04-02 at 12 36 48" src="https://user-images.githubusercontent.com/7696671/78245285-22499c80-74df-11ea-97f2-7bd7b845edb3.png">

Here's the part where the $ref is specified in the OpenAPI document commited to github (looks ok to me): 

<img width="761" alt="Screenshot 2020-04-02 at 12 41 28" src="https://user-images.githubusercontent.com/7696671/78245411-591fb280-74df-11ea-989c-ad4119bc4efb.png">

If I copy over the JSON served at the external url and paste it directly into studio and create a model from it, and reference this local model instead then it all works fine, and the rendered page looks like this:

<img width="928" alt="Screenshot 2020-04-02 at 12 46 06" src="https://user-images.githubusercontent.com/7696671/78245771-f67ae680-74df-11ea-8f13-8b9f1f891ef6.png">

**Environment**
 - Studio version: [e.g. 1.10.2]
 - OS: [Mac OS X 10.14.6]
 - Browser: [Chrome 80]

**Additional context**
- If I change it to another of my external JSON schemas, e.g. [this one](https://api.birminghamurbanobservatory.com/schemas/deployment-get-response.body.json), it renders fine.
- The fact I can create a model from the JSON in studio and it renders fine implies that the JSON schema itself is valid. Also if I paste it into https://www.jsonschemavalidator.net/ it shows no errors either.

**Comment by SiBell** [comment]
This is no longer a problem. You can close this issue.

I don't believe I've changed anything drastic at my end. I suspect an update to Studio has fixed this.

**Comment by danherd** [comment]
I am also having this problem - albeit in slightly different circumstances.

Here is my customer model:

```yaml
title: Customer
type: object
properties:
  title:
    type: string
    maxLength: 255
  first_name:
    type: string
    maxLength: 255
  last_name:
    type: string
    maxLength: 255
  email:
    type: string
    maxLength: 255
    format: email
  phone:
    type: string
    nullable: true
    default: null
    maxLength: 255
required:
  - title
  - first_name
  - last_name
  - email
```

My customer model for new customers:

```yaml
title: New Customer
allOf:
  - $ref: ./Customer.v1.yaml
  - type: object
    properties:
      password:
        type: string
        description: 'Must have at least 8 characters, including a lowercase, uppercase, number and special character.'
        minLength: 8
        format: password
    required:
      - password
```

And finally, my create customer endpoint:

```yaml
  /customers:
    post:
      summary: ''
      operationId: post-customers
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                required:
                  - jwt
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
      parameters: []
      description: Create a new customer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./CustomerNew.v1.yaml
```

This all seems to be fine, but when I view the published documentation, I get this:

![2020-09-23_10-47](https://user-images.githubusercontent.com/659658/93997420-477edf80-fd8b-11ea-8ca5-0d0d3f729577.png)

Am I doing something incorrectly, or is this a bug?
