### ISSUE TITLE
Unexpected schema in docs for items > anyOf

### ISSUE THREAD

**Issue by emorale112** [stoplightio/studio#400]
**Describe the bug**
When publishing an array[object] within models, the docs do not publish the expected schema.

**To Reproduce**

1. Using the following model:
```
title: 1516
type: array
description: ''
x-examples: {}
items:
  anyOf:
    - properties:
        operator:
          type: string
        property:
          type: string
        value:
          type: string
      required:
        - operator
        - property
        - value
    - properties:
        operator:
          type: string
        property:
          type: string
        value:
          type: array
          items:
            type: string
      required:
        - operator
        - property
        - value
    - properties:
        operator:
          type: string
        property:
          type: string
        value:
          type: string
      required:
        - operator
        - property
        - value
    - properties:
        operator:
          type: string
        property:
          type: string
        value:
          type: number
      required:
        - operator
        - property
        - value
    - properties:
        operator:
          type: string
        property:
          type: string
        value:
          type: string
      required:
        - operator
        - property
        - value
  type: object
```
2. Select Publish and either preview or publish
3. Dos do not show model, only an empty array[object]

**Expected behavior**
The defined schema should be published on the Docs

**Screenshots**
![2020-04-24_09-31-40](https://user-images.githubusercontent.com/23023200/80225015-1f3e5980-8610-11ea-9702-781d651b1e72.png)
![2020-04-24_09-32-11 (1)](https://user-images.githubusercontent.com/23023200/80225020-22394a00-8610-11ea-8097-79cb71537824.gif)

**Environment (remove any that are not applicable):**
 - Studio version: 11.1.0
