### ISSUE TITLE
Array Query Params

### ISSUE THREAD

**Issue by dregini** [stoplightio/studio#436]
**Describe the bug**
When creating a query param with type "Array" I can't add any kind of validation. 
I need to add enums and specify the type of the array element's but i can't.

**To Reproduce**

Open/create any endpoint and add a new query param
select array as type
click the validations button ( to add enums)

**Expected behavior**
Possibility to:
 - specify the type of array elements,
 - add enums to array 
 - add serialization style (form/spaceDelimited  etc) and explode true/false

**Screenshots**
![array_no_validation](https://user-images.githubusercontent.com/7930981/82803529-fca69700-9e80-11ea-9212-dc9922057915.PNG)

**Environment (remove any that are not applicable):**
 - Studio version: 1.12.0
 - OS: Windows Server 2012 R2 Datacenter

**Additional context**
created yaml code should be something like this in OpenApi v3: 
```
        - schema:
            type: array
            items:
              type: string
              enum:
                - a
                - b
                - c
          style: form
          explode: true
          in: query
          name: include
          description: array of a b c
```
