### ISSUE TITLE
It would be great if stoplight support enum object

### ISSUE THREAD

**Issue by rainmanhhh** [stoplightio/studio#439]
currently in form view enums could only be string literals, but in openapi.yaml enums could be defined as objects:
```yaml
enum:
  - value: 1
    description: the first value
  - value: 2
    description: the second value
```
