### ISSUE TITLE
No way to choose right schema from dropdown box in Endpoint

### ISSUE THREAD

**Issue by boskiv** [stoplightio/studio#52]
> Based on https://community.stoplight.io/t/security-schemas-in-stoplight-studio/796

**Describe the bug**
You will be confused with security configuration in the endpoint when you have more than one security schemas of one type but a different kind.

**To Reproduce**

1. Create a 2 security schemas of http type. One for basic auth, one for bearer
2. Create an endpoint GET /auth/login that should get basic auth and return a JWT token
3. See 2 `http` options in security dropdown box

**Expected behavior**
I prefer to use `key` instead of `schema_n` as a dropdown value here.
And also when I create a schema I prefer to use a `kind` as a `key` instead of `schema_n`
```
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: Bearer
      description: bearer
    basic:
      type: http
      scheme: Basic
      description: basic
    scheme_2: <- i think apikey here will be more verbose
      name: API Key
      type: apiKey
```

**Screenshots**
![Screenshot 2019-08-15 at 3 10 36 PM](https://user-images.githubusercontent.com/1939783/63094960-95af9580-bf72-11e9-886b-88c9dbf3fbf4.png)
![Screenshot 2019-08-15 at 3 10 29 PM](https://user-images.githubusercontent.com/1939783/63094969-9ba57680-bf72-11e9-818e-1a35bca37b29.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.0.0.5249
 - OS: OSX Mojave 10.14.6 (18G87)
 - Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**

**Comment by boskiv** [comment]
I have found, that if I add `name` attribute here
```
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: Bearer
      description: bearer
      name: bearer
    basic:
      type: http
      name: basic
      scheme: Basic
      description: basic
```
it fixes dropbox issue
![Screenshot 2019-08-15 at 3 51 26 PM](https://user-images.githubusercontent.com/1939783/63095714-95b09500-bf74-11e9-9fcb-7b0fcca600b0.png)

but add some validation errors

![Screenshot 2019-08-15 at 3 49 34 PM](https://user-images.githubusercontent.com/1939783/63095658-7154b880-bf74-11e9-90c3-c0b17e11feb5.png)
