### ISSUE TITLE
Support parameters as separate files

### ISSUE THREAD

**Issue by dantheman999301** [stoplightio/studio#545]
**User story.**
As an API designer, I can add different types of models (e.g. headers, query parameters) outside of an API yaml, so that I can more easily share common models between microservices.

**Is your feature request related to a problem?**
Currently in Studio when splitting up an API into multiple files, you can just move your models into different files. This is really useful as when you use the UI you can see them and edit them in the form view as a single entity. They can also then be directly referenced easily from other projects.

However right now this is restricted just to what Studio detects as models. Other valid external YAML such as headers, or query parameters do not show up. They do appear in `Files` but cannot be seen in `APIs` and you cannot edit them in the `Form` view.

**Describe the solution you'd like**
It would be great if we could create and edit things that would normally go into `components/parameters` as outside files.

**Additional context**
It might also be worth considering files that have an array of parameters in. For example:
```
example-1:
  name: example-1
  in: query
  required: false
  schema:
    type: string
  description: An example query param
example-2:
  in: header
  required: false
  schema:
    type: string
  description: An example header param
```

Although that might be a separate story.
