### ISSUE TITLE
JSE > Array of objects displays as "array[objectnull]" in Forms view

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#70]
**Describe the bug**

When using an array of object types in the JSON schema editor, it displays in the Forms view as "array[objectnull]".

**To Reproduce**

With model file:
```
type: object
properties:
  code:
    type: string
  data:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
```

Displays as:

![image](https://user-images.githubusercontent.com/4060903/63621920-e0588f80-c5ba-11e9-89fa-964ac83fd817.png)

**Expected behavior**

It should just be "array[object]".
