### ISSUE TITLE
Add support for operation level servers

### ISSUE THREAD

**Issue by jalleyne** [stoplightio/studio#88]
**Describe the bug**
When defining the servers list, the UI suggests i can add several server urls. The first time i added this my endpoints did not have a server defined. Now that i only have 1 its now showing up.

**To Reproduce**

1. Given this OpenAPI servers definition: 

```
servers:
  - description: Localhost
    url: 'http://localhost:3000'
  - url: 'https://dev-mi-api.mydomain.com'
    description: Dev
  - url: 'https://staging-api.mydomain.com'
    description: Staging
  - url: 'https://api.mydomain.com'
    description: Production
```

2. Click a path entity under the paths folder 
3. On the top line that defines the url, the server button says to define a server url

**Expected behavior**
I would expect the button that sits next to the url to be a dropdown to select the server i want to use or at least show the first server i defined in the list.

**Screenshots**
![Screen Shot 2019-09-05 at 10 54 26 AM](https://user-images.githubusercontent.com/163205/64353340-995f9680-cfcb-11e9-909a-2cccca744ee8.png)

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.0.1 (1.0.1.5455)
 - OS: macOS 10.14.6
 - Browser: Native app

**Additional context**
If i remove the other server definitions, so only 1 remains and refresh the app (cmd + r) i see the server definition show up.
